In [1]:
import numpy as np
import fractions
import scipy.linalg as ln

In [2]:
A = np.random.random_sample((3, 3))

A = np.matrix(A)
print(A)

[[0.20375242 0.40861315 0.828105  ]
 [0.92324444 0.82986077 0.71526666]
 [0.28377695 0.08088559 0.83279633]]


In [3]:
eigvalue, eigvectors = np.linalg.eig(A)
print("eigvalue: ", eigvalue)
print("eigvectors:")
print(eigvectors)

eigvalue:  [-0.25875485  1.53099504  0.59416933]
eigvectors:
[[-0.80327224  0.43614258 -0.08453338]
 [ 0.57187997  0.85635372 -0.9088008 ]
 [ 0.16645422  0.27647414  0.40857705]]


In [4]:
e_Lambda = np.eye(np.size(A, 0))*(np.exp(eigvalue))
print(e_Lambda)

[[0.77201226 0.         0.        ]
 [0.         4.62277437 0.        ]
 [0.         0.         1.81152554]]


In [5]:
e_A = eigvectors*e_Lambda*eigvectors.I
print(e_A)

[[1.76552093 0.84876429 1.87839416]
 [1.96915947 2.78748774 2.57825286]
 [0.61832427 0.32093074 2.65330349]]


In [6]:
e_A2 = ln.expm(A)
print(e_A2)

[[1.76552093 0.84876429 1.87839416]
 [1.96915947 2.78748774 2.57825286]
 [0.61832427 0.32093074 2.65330349]]


In [7]:
np.testing.assert_allclose(e_A, e_A2)
print(e_A - e_A2)

[[-4.44089210e-16  0.00000000e+00 -6.66133815e-16]
 [-1.11022302e-15 -8.88178420e-16 -1.33226763e-15]
 [-5.55111512e-16 -2.22044605e-16 -4.44089210e-16]]
